version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-docker
    volumes:
      - 'docker-volumes/mongo/data:/data/db'
    ports:
      - 27018:27017
  fun5-b-backend:
    depend_on:
      - fun5-mongo
    build:
      context: .
      dockerfile: Dockerfile
    image: fun5-b-backend
    container_name: fun5-b-backend
    ports:
      - 7001:7001
